# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.25.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.25.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/fabian/Documents/Projects/CPP/Table Tennis"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/fabian/Documents/Projects/CPP/Table Tennis"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.25.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.25.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/fabian/Documents/Projects/CPP/Table Tennis/CMakeFiles" "/Users/fabian/Documents/Projects/CPP/Table Tennis//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/fabian/Documents/Projects/CPP/Table Tennis/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TableTennis

# Build rule for target.
TableTennis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TableTennis
.PHONY : TableTennis

# fast build rule for target.
TableTennis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/build
.PHONY : TableTennis/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/main.cpp.s
.PHONY : main.cpp.s

src/components/ballmovement.o: src/components/ballmovement.cpp.o
.PHONY : src/components/ballmovement.o

# target to build an object file
src/components/ballmovement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/ballmovement.cpp.o
.PHONY : src/components/ballmovement.cpp.o

src/components/ballmovement.i: src/components/ballmovement.cpp.i
.PHONY : src/components/ballmovement.i

# target to preprocess a source file
src/components/ballmovement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/ballmovement.cpp.i
.PHONY : src/components/ballmovement.cpp.i

src/components/ballmovement.s: src/components/ballmovement.cpp.s
.PHONY : src/components/ballmovement.s

# target to generate assembly for a file
src/components/ballmovement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/ballmovement.cpp.s
.PHONY : src/components/ballmovement.cpp.s

src/components/bubbledrawer.o: src/components/bubbledrawer.cpp.o
.PHONY : src/components/bubbledrawer.o

# target to build an object file
src/components/bubbledrawer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/bubbledrawer.cpp.o
.PHONY : src/components/bubbledrawer.cpp.o

src/components/bubbledrawer.i: src/components/bubbledrawer.cpp.i
.PHONY : src/components/bubbledrawer.i

# target to preprocess a source file
src/components/bubbledrawer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/bubbledrawer.cpp.i
.PHONY : src/components/bubbledrawer.cpp.i

src/components/bubbledrawer.s: src/components/bubbledrawer.cpp.s
.PHONY : src/components/bubbledrawer.s

# target to generate assembly for a file
src/components/bubbledrawer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/bubbledrawer.cpp.s
.PHONY : src/components/bubbledrawer.cpp.s

src/components/button.o: src/components/button.cpp.o
.PHONY : src/components/button.o

# target to build an object file
src/components/button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/button.cpp.o
.PHONY : src/components/button.cpp.o

src/components/button.i: src/components/button.cpp.i
.PHONY : src/components/button.i

# target to preprocess a source file
src/components/button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/button.cpp.i
.PHONY : src/components/button.cpp.i

src/components/button.s: src/components/button.cpp.s
.PHONY : src/components/button.s

# target to generate assembly for a file
src/components/button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/button.cpp.s
.PHONY : src/components/button.cpp.s

src/components/component.o: src/components/component.cpp.o
.PHONY : src/components/component.o

# target to build an object file
src/components/component.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/component.cpp.o
.PHONY : src/components/component.cpp.o

src/components/component.i: src/components/component.cpp.i
.PHONY : src/components/component.i

# target to preprocess a source file
src/components/component.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/component.cpp.i
.PHONY : src/components/component.cpp.i

src/components/component.s: src/components/component.cpp.s
.PHONY : src/components/component.s

# target to generate assembly for a file
src/components/component.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/component.cpp.s
.PHONY : src/components/component.cpp.s

src/components/debugger.o: src/components/debugger.cpp.o
.PHONY : src/components/debugger.o

# target to build an object file
src/components/debugger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/debugger.cpp.o
.PHONY : src/components/debugger.cpp.o

src/components/debugger.i: src/components/debugger.cpp.i
.PHONY : src/components/debugger.i

# target to preprocess a source file
src/components/debugger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/debugger.cpp.i
.PHONY : src/components/debugger.cpp.i

src/components/debugger.s: src/components/debugger.cpp.s
.PHONY : src/components/debugger.s

# target to generate assembly for a file
src/components/debugger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/debugger.cpp.s
.PHONY : src/components/debugger.cpp.s

src/components/menutitle.o: src/components/menutitle.cpp.o
.PHONY : src/components/menutitle.o

# target to build an object file
src/components/menutitle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/menutitle.cpp.o
.PHONY : src/components/menutitle.cpp.o

src/components/menutitle.i: src/components/menutitle.cpp.i
.PHONY : src/components/menutitle.i

# target to preprocess a source file
src/components/menutitle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/menutitle.cpp.i
.PHONY : src/components/menutitle.cpp.i

src/components/menutitle.s: src/components/menutitle.cpp.s
.PHONY : src/components/menutitle.s

# target to generate assembly for a file
src/components/menutitle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/menutitle.cpp.s
.PHONY : src/components/menutitle.cpp.s

src/components/powerbar.o: src/components/powerbar.cpp.o
.PHONY : src/components/powerbar.o

# target to build an object file
src/components/powerbar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/powerbar.cpp.o
.PHONY : src/components/powerbar.cpp.o

src/components/powerbar.i: src/components/powerbar.cpp.i
.PHONY : src/components/powerbar.i

# target to preprocess a source file
src/components/powerbar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/powerbar.cpp.i
.PHONY : src/components/powerbar.cpp.i

src/components/powerbar.s: src/components/powerbar.cpp.s
.PHONY : src/components/powerbar.s

# target to generate assembly for a file
src/components/powerbar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/powerbar.cpp.s
.PHONY : src/components/powerbar.cpp.s

src/components/shadowtransformer.o: src/components/shadowtransformer.cpp.o
.PHONY : src/components/shadowtransformer.o

# target to build an object file
src/components/shadowtransformer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/shadowtransformer.cpp.o
.PHONY : src/components/shadowtransformer.cpp.o

src/components/shadowtransformer.i: src/components/shadowtransformer.cpp.i
.PHONY : src/components/shadowtransformer.i

# target to preprocess a source file
src/components/shadowtransformer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/shadowtransformer.cpp.i
.PHONY : src/components/shadowtransformer.cpp.i

src/components/shadowtransformer.s: src/components/shadowtransformer.cpp.s
.PHONY : src/components/shadowtransformer.s

# target to generate assembly for a file
src/components/shadowtransformer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/shadowtransformer.cpp.s
.PHONY : src/components/shadowtransformer.cpp.s

src/components/spriterenderer.o: src/components/spriterenderer.cpp.o
.PHONY : src/components/spriterenderer.o

# target to build an object file
src/components/spriterenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/spriterenderer.cpp.o
.PHONY : src/components/spriterenderer.cpp.o

src/components/spriterenderer.i: src/components/spriterenderer.cpp.i
.PHONY : src/components/spriterenderer.i

# target to preprocess a source file
src/components/spriterenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/spriterenderer.cpp.i
.PHONY : src/components/spriterenderer.cpp.i

src/components/spriterenderer.s: src/components/spriterenderer.cpp.s
.PHONY : src/components/spriterenderer.s

# target to generate assembly for a file
src/components/spriterenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/spriterenderer.cpp.s
.PHONY : src/components/spriterenderer.cpp.s

src/components/textrenderer.o: src/components/textrenderer.cpp.o
.PHONY : src/components/textrenderer.o

# target to build an object file
src/components/textrenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/textrenderer.cpp.o
.PHONY : src/components/textrenderer.cpp.o

src/components/textrenderer.i: src/components/textrenderer.cpp.i
.PHONY : src/components/textrenderer.i

# target to preprocess a source file
src/components/textrenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/textrenderer.cpp.i
.PHONY : src/components/textrenderer.cpp.i

src/components/textrenderer.s: src/components/textrenderer.cpp.s
.PHONY : src/components/textrenderer.s

# target to generate assembly for a file
src/components/textrenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/textrenderer.cpp.s
.PHONY : src/components/textrenderer.cpp.s

src/components/transform.o: src/components/transform.cpp.o
.PHONY : src/components/transform.o

# target to build an object file
src/components/transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/transform.cpp.o
.PHONY : src/components/transform.cpp.o

src/components/transform.i: src/components/transform.cpp.i
.PHONY : src/components/transform.i

# target to preprocess a source file
src/components/transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/transform.cpp.i
.PHONY : src/components/transform.cpp.i

src/components/transform.s: src/components/transform.cpp.s
.PHONY : src/components/transform.s

# target to generate assembly for a file
src/components/transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/components/transform.cpp.s
.PHONY : src/components/transform.cpp.s

src/entity/entity.o: src/entity/entity.cpp.o
.PHONY : src/entity/entity.o

# target to build an object file
src/entity/entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/entity/entity.cpp.o
.PHONY : src/entity/entity.cpp.o

src/entity/entity.i: src/entity/entity.cpp.i
.PHONY : src/entity/entity.i

# target to preprocess a source file
src/entity/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/entity/entity.cpp.i
.PHONY : src/entity/entity.cpp.i

src/entity/entity.s: src/entity/entity.cpp.s
.PHONY : src/entity/entity.s

# target to generate assembly for a file
src/entity/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/entity/entity.cpp.s
.PHONY : src/entity/entity.cpp.s

src/entity/entitymanager.o: src/entity/entitymanager.cpp.o
.PHONY : src/entity/entitymanager.o

# target to build an object file
src/entity/entitymanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/entity/entitymanager.cpp.o
.PHONY : src/entity/entitymanager.cpp.o

src/entity/entitymanager.i: src/entity/entitymanager.cpp.i
.PHONY : src/entity/entitymanager.i

# target to preprocess a source file
src/entity/entitymanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/entity/entitymanager.cpp.i
.PHONY : src/entity/entitymanager.cpp.i

src/entity/entitymanager.s: src/entity/entitymanager.cpp.s
.PHONY : src/entity/entitymanager.s

# target to generate assembly for a file
src/entity/entitymanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/entity/entitymanager.cpp.s
.PHONY : src/entity/entitymanager.cpp.s

src/gameplay/gamemanager.o: src/gameplay/gamemanager.cpp.o
.PHONY : src/gameplay/gamemanager.o

# target to build an object file
src/gameplay/gamemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/gameplay/gamemanager.cpp.o
.PHONY : src/gameplay/gamemanager.cpp.o

src/gameplay/gamemanager.i: src/gameplay/gamemanager.cpp.i
.PHONY : src/gameplay/gamemanager.i

# target to preprocess a source file
src/gameplay/gamemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/gameplay/gamemanager.cpp.i
.PHONY : src/gameplay/gamemanager.cpp.i

src/gameplay/gamemanager.s: src/gameplay/gamemanager.cpp.s
.PHONY : src/gameplay/gamemanager.s

# target to generate assembly for a file
src/gameplay/gamemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/gameplay/gamemanager.cpp.s
.PHONY : src/gameplay/gamemanager.cpp.s

src/menu/pane.o: src/menu/pane.cpp.o
.PHONY : src/menu/pane.o

# target to build an object file
src/menu/pane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/menu/pane.cpp.o
.PHONY : src/menu/pane.cpp.o

src/menu/pane.i: src/menu/pane.cpp.i
.PHONY : src/menu/pane.i

# target to preprocess a source file
src/menu/pane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/menu/pane.cpp.i
.PHONY : src/menu/pane.cpp.i

src/menu/pane.s: src/menu/pane.cpp.s
.PHONY : src/menu/pane.s

# target to generate assembly for a file
src/menu/pane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/menu/pane.cpp.s
.PHONY : src/menu/pane.cpp.s

src/panes/game.o: src/panes/game.cpp.o
.PHONY : src/panes/game.o

# target to build an object file
src/panes/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/panes/game.cpp.o
.PHONY : src/panes/game.cpp.o

src/panes/game.i: src/panes/game.cpp.i
.PHONY : src/panes/game.i

# target to preprocess a source file
src/panes/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/panes/game.cpp.i
.PHONY : src/panes/game.cpp.i

src/panes/game.s: src/panes/game.cpp.s
.PHONY : src/panes/game.s

# target to generate assembly for a file
src/panes/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/panes/game.cpp.s
.PHONY : src/panes/game.cpp.s

src/panes/home.o: src/panes/home.cpp.o
.PHONY : src/panes/home.o

# target to build an object file
src/panes/home.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/panes/home.cpp.o
.PHONY : src/panes/home.cpp.o

src/panes/home.i: src/panes/home.cpp.i
.PHONY : src/panes/home.i

# target to preprocess a source file
src/panes/home.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/panes/home.cpp.i
.PHONY : src/panes/home.cpp.i

src/panes/home.s: src/panes/home.cpp.s
.PHONY : src/panes/home.s

# target to generate assembly for a file
src/panes/home.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/panes/home.cpp.s
.PHONY : src/panes/home.cpp.s

src/render/fontmanager.o: src/render/fontmanager.cpp.o
.PHONY : src/render/fontmanager.o

# target to build an object file
src/render/fontmanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/render/fontmanager.cpp.o
.PHONY : src/render/fontmanager.cpp.o

src/render/fontmanager.i: src/render/fontmanager.cpp.i
.PHONY : src/render/fontmanager.i

# target to preprocess a source file
src/render/fontmanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/render/fontmanager.cpp.i
.PHONY : src/render/fontmanager.cpp.i

src/render/fontmanager.s: src/render/fontmanager.cpp.s
.PHONY : src/render/fontmanager.s

# target to generate assembly for a file
src/render/fontmanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/render/fontmanager.cpp.s
.PHONY : src/render/fontmanager.cpp.s

src/render/renderwindow.o: src/render/renderwindow.cpp.o
.PHONY : src/render/renderwindow.o

# target to build an object file
src/render/renderwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/render/renderwindow.cpp.o
.PHONY : src/render/renderwindow.cpp.o

src/render/renderwindow.i: src/render/renderwindow.cpp.i
.PHONY : src/render/renderwindow.i

# target to preprocess a source file
src/render/renderwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/render/renderwindow.cpp.i
.PHONY : src/render/renderwindow.cpp.i

src/render/renderwindow.s: src/render/renderwindow.cpp.s
.PHONY : src/render/renderwindow.s

# target to generate assembly for a file
src/render/renderwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/render/renderwindow.cpp.s
.PHONY : src/render/renderwindow.cpp.s

src/sound/soundmanager.o: src/sound/soundmanager.cpp.o
.PHONY : src/sound/soundmanager.o

# target to build an object file
src/sound/soundmanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/sound/soundmanager.cpp.o
.PHONY : src/sound/soundmanager.cpp.o

src/sound/soundmanager.i: src/sound/soundmanager.cpp.i
.PHONY : src/sound/soundmanager.i

# target to preprocess a source file
src/sound/soundmanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/sound/soundmanager.cpp.i
.PHONY : src/sound/soundmanager.cpp.i

src/sound/soundmanager.s: src/sound/soundmanager.cpp.s
.PHONY : src/sound/soundmanager.s

# target to generate assembly for a file
src/sound/soundmanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/sound/soundmanager.cpp.s
.PHONY : src/sound/soundmanager.cpp.s

src/utility/circle.o: src/utility/circle.cpp.o
.PHONY : src/utility/circle.o

# target to build an object file
src/utility/circle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/circle.cpp.o
.PHONY : src/utility/circle.cpp.o

src/utility/circle.i: src/utility/circle.cpp.i
.PHONY : src/utility/circle.i

# target to preprocess a source file
src/utility/circle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/circle.cpp.i
.PHONY : src/utility/circle.cpp.i

src/utility/circle.s: src/utility/circle.cpp.s
.PHONY : src/utility/circle.s

# target to generate assembly for a file
src/utility/circle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/circle.cpp.s
.PHONY : src/utility/circle.cpp.s

src/utility/mathutil.o: src/utility/mathutil.cpp.o
.PHONY : src/utility/mathutil.o

# target to build an object file
src/utility/mathutil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/mathutil.cpp.o
.PHONY : src/utility/mathutil.cpp.o

src/utility/mathutil.i: src/utility/mathutil.cpp.i
.PHONY : src/utility/mathutil.i

# target to preprocess a source file
src/utility/mathutil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/mathutil.cpp.i
.PHONY : src/utility/mathutil.cpp.i

src/utility/mathutil.s: src/utility/mathutil.cpp.s
.PHONY : src/utility/mathutil.s

# target to generate assembly for a file
src/utility/mathutil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/mathutil.cpp.s
.PHONY : src/utility/mathutil.cpp.s

src/utility/vector2int.o: src/utility/vector2int.cpp.o
.PHONY : src/utility/vector2int.o

# target to build an object file
src/utility/vector2int.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/vector2int.cpp.o
.PHONY : src/utility/vector2int.cpp.o

src/utility/vector2int.i: src/utility/vector2int.cpp.i
.PHONY : src/utility/vector2int.i

# target to preprocess a source file
src/utility/vector2int.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/vector2int.cpp.i
.PHONY : src/utility/vector2int.cpp.i

src/utility/vector2int.s: src/utility/vector2int.cpp.s
.PHONY : src/utility/vector2int.s

# target to generate assembly for a file
src/utility/vector2int.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/vector2int.cpp.s
.PHONY : src/utility/vector2int.cpp.s

src/utility/vector3.o: src/utility/vector3.cpp.o
.PHONY : src/utility/vector3.o

# target to build an object file
src/utility/vector3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/vector3.cpp.o
.PHONY : src/utility/vector3.cpp.o

src/utility/vector3.i: src/utility/vector3.cpp.i
.PHONY : src/utility/vector3.i

# target to preprocess a source file
src/utility/vector3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/vector3.cpp.i
.PHONY : src/utility/vector3.cpp.i

src/utility/vector3.s: src/utility/vector3.cpp.s
.PHONY : src/utility/vector3.s

# target to generate assembly for a file
src/utility/vector3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/vector3.cpp.s
.PHONY : src/utility/vector3.cpp.s

src/utility/vector3int.o: src/utility/vector3int.cpp.o
.PHONY : src/utility/vector3int.o

# target to build an object file
src/utility/vector3int.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/vector3int.cpp.o
.PHONY : src/utility/vector3int.cpp.o

src/utility/vector3int.i: src/utility/vector3int.cpp.i
.PHONY : src/utility/vector3int.i

# target to preprocess a source file
src/utility/vector3int.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/vector3int.cpp.i
.PHONY : src/utility/vector3int.cpp.i

src/utility/vector3int.s: src/utility/vector3int.cpp.s
.PHONY : src/utility/vector3int.s

# target to generate assembly for a file
src/utility/vector3int.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TableTennis.dir/build.make CMakeFiles/TableTennis.dir/src/utility/vector3int.cpp.s
.PHONY : src/utility/vector3int.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TableTennis"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/components/ballmovement.o"
	@echo "... src/components/ballmovement.i"
	@echo "... src/components/ballmovement.s"
	@echo "... src/components/bubbledrawer.o"
	@echo "... src/components/bubbledrawer.i"
	@echo "... src/components/bubbledrawer.s"
	@echo "... src/components/button.o"
	@echo "... src/components/button.i"
	@echo "... src/components/button.s"
	@echo "... src/components/component.o"
	@echo "... src/components/component.i"
	@echo "... src/components/component.s"
	@echo "... src/components/debugger.o"
	@echo "... src/components/debugger.i"
	@echo "... src/components/debugger.s"
	@echo "... src/components/menutitle.o"
	@echo "... src/components/menutitle.i"
	@echo "... src/components/menutitle.s"
	@echo "... src/components/powerbar.o"
	@echo "... src/components/powerbar.i"
	@echo "... src/components/powerbar.s"
	@echo "... src/components/shadowtransformer.o"
	@echo "... src/components/shadowtransformer.i"
	@echo "... src/components/shadowtransformer.s"
	@echo "... src/components/spriterenderer.o"
	@echo "... src/components/spriterenderer.i"
	@echo "... src/components/spriterenderer.s"
	@echo "... src/components/textrenderer.o"
	@echo "... src/components/textrenderer.i"
	@echo "... src/components/textrenderer.s"
	@echo "... src/components/transform.o"
	@echo "... src/components/transform.i"
	@echo "... src/components/transform.s"
	@echo "... src/entity/entity.o"
	@echo "... src/entity/entity.i"
	@echo "... src/entity/entity.s"
	@echo "... src/entity/entitymanager.o"
	@echo "... src/entity/entitymanager.i"
	@echo "... src/entity/entitymanager.s"
	@echo "... src/gameplay/gamemanager.o"
	@echo "... src/gameplay/gamemanager.i"
	@echo "... src/gameplay/gamemanager.s"
	@echo "... src/menu/pane.o"
	@echo "... src/menu/pane.i"
	@echo "... src/menu/pane.s"
	@echo "... src/panes/game.o"
	@echo "... src/panes/game.i"
	@echo "... src/panes/game.s"
	@echo "... src/panes/home.o"
	@echo "... src/panes/home.i"
	@echo "... src/panes/home.s"
	@echo "... src/render/fontmanager.o"
	@echo "... src/render/fontmanager.i"
	@echo "... src/render/fontmanager.s"
	@echo "... src/render/renderwindow.o"
	@echo "... src/render/renderwindow.i"
	@echo "... src/render/renderwindow.s"
	@echo "... src/sound/soundmanager.o"
	@echo "... src/sound/soundmanager.i"
	@echo "... src/sound/soundmanager.s"
	@echo "... src/utility/circle.o"
	@echo "... src/utility/circle.i"
	@echo "... src/utility/circle.s"
	@echo "... src/utility/mathutil.o"
	@echo "... src/utility/mathutil.i"
	@echo "... src/utility/mathutil.s"
	@echo "... src/utility/vector2int.o"
	@echo "... src/utility/vector2int.i"
	@echo "... src/utility/vector2int.s"
	@echo "... src/utility/vector3.o"
	@echo "... src/utility/vector3.i"
	@echo "... src/utility/vector3.s"
	@echo "... src/utility/vector3int.o"
	@echo "... src/utility/vector3int.i"
	@echo "... src/utility/vector3int.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

